name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Lint & Static Analysis

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, mbstring, zip
        coverage: none

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Coding Style
      run: composer test:lint

    - name: Static Analysis
      run: composer test:types
